project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: "src/locales"

preserve_hierarchy: true

files:
  - source: "jp/**/*"
    translation: "/%two_letters_code%/**/%original_file_name%"
    dest: "voicevox_blog/%two_letters_code%/%original_file_name%"
