name: Crowdin

on:
  push:
    # branches: [master] # TODO: あとで戻す
  workflow_dispatch:

jobs:
  crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: crowdin action
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          download_translations: true
          skip_untranslated_strings: true
          export_only_approved: true
          create_pull_request: true
          pull_request_base_branch_name: "try-crowdin" # TODO: あとでmasterにする
        env:
          GITHUB_TOKEN: ${{ secrets.CROWDIN_GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
