name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Lint
        run: pnpm run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Build
        run: pnpm run build

  e2e:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Setup playwright
        run: pnpm exec playwright install

      - name: Build
        run: pnpm run preview-build

      - name: Test e2e
        run: pnpm run test:e2e

      - name: Upload playwright report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/

  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: typos-action
        uses: crate-ci/typos@v1.12.12
